"""book url cover

Revision ID: 219f01a918fd
Revises: f0551883a2f7
Create Date: 2025-02-03 10:40:59.776459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219f01a918fd'
down_revision = 'f0551883a2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_img')
    # ### end Alembic commands ###
