"""book image column

Revision ID: 5b0cb71a008d
Revises: b490a1efc6ca
Create Date: 2025-04-20 21:35:35.344058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0cb71a008d'
down_revision = 'b490a1efc6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
