"""removing subject column

Revision ID: da086b9aa1b6
Revises: 9de99fa5cc24
Create Date: 2025-05-11 16:11:45.397801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da086b9aa1b6'
down_revision = '9de99fa5cc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('subject', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
